//! Event generated by onchain events.
use std::fmt::Debug;

use crate::bitcoin::BlockHeader;
use crate::bitcoin::{locktime::Height, Txid};
use crate::bitcoin::{Block, Transaction};

#[derive(Clone)]
pub enum OnChainEvent {
    NewBlock(Block),
    NewBestBlock((BlockHeader, Height)),
    FeeEstimation(u32),
    SendRawTransaction(Transaction),
    ConfirmedTransaction((Transaction, u32, BlockHeader, Height)),
    DiscardedTransaction(Txid),
    UnconfirmedTransaction(Txid),
}

impl Debug for OnChainEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ConfirmedTransaction((tx, idx, header, height)) => write!(
                f,
                "ConfirmedTransaction(txid: {}, idx {idx}, block: {:?}, height: {height})",
                tx.txid(),
                header
            ),
            Self::NewBestBlock((header, height)) => {
                write!(f, "NewBestBlock({}, {height})", header.block_hash())
            }
            Self::NewBlock(block) => write!(f, "NewBlock({})", block.block_hash()),
            Self::SendRawTransaction(tx) => write!(f, "SendRawTransaction({})", tx.txid()),
            Self::UnconfirmedTransaction(tx) => write!(f, "UnconfirmedTransaction({})", tx),
            _ => write!(f, "Debug fmt not unsupported"),
        }
    }
}
