//! Event generated by onchain events.
use crate::bitcoin::{Block, Transaction};
use crate::error;

#[derive(Debug, Clone)]
pub enum OnChainEvent {
    NewBlock(Block),
    // FIXME: add a model for the fee estimation.
    FeeEstimation(u32),
    SendRawTransaction(Transaction),
}
