[package]
name = "lampo-watchtower"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning = { workspace = true }
lightning-persister = { workspace = true }

anyhow = "1.0.102"
bitcoin = { version = "0.32", features = ["serde"] }
chacha20poly1305 = "0.10"
hex = { version = "0.4.3", features = ["serde"] }
log = "0.4"
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
