[package]
name = "lampo-plugin-manager"
version = "0.1.0"
edition = "2021"


[dependencies]
lampo-jsonrpc = { path = "../lampo-jsonrpc", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
popol = "2.2.0 "
log = "0.4.17"
