name: lampo_dart
description: Dart binding for the Lightning Network node Lampo.
version: 0.0.1-alpha.2
repository: https://github.com/dart-lightning/lampo.r

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
    ffi: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  ffigen: ^4.1.2
  logger: ^1.3.0

ffigen:
  name: 'LampoFFI'
  description: 'Lampo Deamon FFI to write a lightning node in dart'
  output: 'lib/ffi/generated_bindings.dart'
  headers:
    entry-points:
      - '../../lampo-ffi/liblampo.h'
