name: lampo_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
    ffi: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  ffigen: ^4.1.2

ffigen:
  name: 'LampoFFI'
  description: 'Lampo Deamon FFI to write a lightning node in dart'
  output: 'lib/ffi/generated_bindings.dart'
  headers:
    entry-points:
      - '../../lampo-c-ffi/liblampo.h'
