//! Type-erased custom Lightning messages.
//!
//! LDK's `CustomMessageHandler` carries an associated `CustomMessage` type, so it is not
//! dyn-safe. Plugins register [`LampoMsgHandler`] implementations with lampod's
//! type-erased router, which owns a single wire type ([`LampoWireMessage`]).

use crate::bitcoin::secp256k1::PublicKey;
use crate::ldk::io;
use crate::ldk::ln::msgs::{Init, LightningError};
use crate::ldk::ln::wire;
use crate::ldk::types::features::{InitFeatures, NodeFeatures};
use crate::ldk::util::ser::{Writeable, Writer};

/// A custom Lightning message captured as a type id plus raw payload bytes.
///
/// The type-erased router uses this as its `CustomMessageHandler::CustomMessage`
/// so plugins can decode their own formats without lampod naming them.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LampoWireMessage {
    /// BOLT 1 message type number.
    pub type_id: u16,
    /// Raw payload (no type prefix, no length prefix).
    pub payload: Vec<u8>,
}

impl Writeable for LampoWireMessage {
    fn write<W: Writer>(&self, writer: &mut W) -> Result<(), io::Error> {
        writer.write_all(&self.payload)
    }
}

impl wire::Type for LampoWireMessage {
    fn type_id(&self) -> u16 {
        self.type_id
    }
}

/// Plugin hook for custom peer-to-peer messages.
///
/// Mirrors [`crate::handler::ExternalHandler`]: lampod owns a registry, plugins
/// implement this trait and register after `LampoDaemon::init`.
pub trait LampoMsgHandler: Send + Sync {
    /// Whether this handler claims `type_id`.
    fn handles(&self, type_id: u16) -> bool;

    /// Handle a custom message whose type this handler claimed.
    fn handle_custom_message(
        &self,
        type_id: u16,
        payload: &[u8],
        sender_node_id: PublicKey,
    ) -> Result<(), LightningError>;

    /// Drain outbound custom messages generated by this handler.
    fn get_and_clear_pending_msg(&self) -> Vec<(PublicKey, LampoWireMessage)>;

    /// A peer disconnected.
    fn peer_disconnected(&self, their_node_id: PublicKey);

    /// A peer connected. Returning `Err(())` asks the peer manager to disconnect.
    fn peer_connected(&self, their_node_id: PublicKey, msg: &Init, inbound: bool)
        -> Result<(), ()>;

    /// Feature bits this handler wants advertised in `node_announcement`.
    fn provided_node_features(&self) -> NodeFeatures;

    /// Feature bits this handler wants sent in `init` to `their_node_id`.
    fn provided_init_features(&self, their_node_id: PublicKey) -> InitFeatures;
}
