name: lnprototest testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 1 1,15 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lnprototest testing
        run: |
          docker build -f docker/Dockerfile -t lampo-ci-ubuntu .
          docker run -e lampo-ci-ubuntu