name: lnprototest testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 1 1,15 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: lnprototest testing
        env:
          PROTO_TEST: 1
        run: |
          docker build -f docker/Dockerfile.lnprototest -t lampo-ci-ubuntu .
          docker run -e PROTO_TEST=1 lampo-ci-ubuntu
